version: '3.4'
volumes:
  zt-data: {}
  acloud_data: {}
services:
  ryo-client.avado.dnp.dappnode.eth:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: ryo-client.avado.dnp.dappnode.eth
    image: 'ryo-client.avado.dnp.dappnode.eth:0.0.19'
    network_mode: host
    privileged: true
    dns: 172.33.1.2
    ports:
      - '1936:1936'
    volumes:
      - 'zt-data:/zt-data'
      - 'acloud_data:/data/acloud'
    restart: always
